name = "Kubiki Q3 2026"
author = "Tapeline"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee56a6aea86e5cbdc542b7c56931831b629ca758fa5c5cec3d6128f247000e26"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
