name = "Kubiki Q3 2026"
author = "Tapeline"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e700890b2829a1dbffe4370c0fb73f25bed849613e1713c21e64086f7584321b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
