name = "Kubiki Q3 2026"
author = "Tapeline"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0880108e1d1df76264776c8cd21d3126be44ca88c6054e386c41e1fc778cf3a5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
