name: Build pack

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: 22
          script: |
            cd conf
            sh sync.sh

  release:
    name: Create release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refresh Packwiz Index
        working-directory: modpack
        run: packwiz refresh

      - name: Resolve and Download All Mods
        working-directory: modpack
        run: |
          packwiz serve &
          SERVER_PID=$!

          sleep 2

          mkdir dist
          cd dist

          wget https://github.com/packwiz/packwiz-installer-bootstrap/releases/latest/download/packwiz-installer-bootstrap.jar

          java -jar packwiz-installer-bootstrap.jar http://localhost:8080/pack.toml

          rm packwiz-installer*

          kill $SERVER_PID

      - name: Zip the Final Distribution
        run: |
          cd modpack/dist
          zip -r ../pack.zip .

      - name: Update release
        run: gh release upload ${{ github.ref_name }} modpack/pack.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
